version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Make output directory
          command: mkdir bin
      - run:
          name: Build & Test
          command: |
            ./docker-make all

      - persist_to_workspace:
          root: bin
          paths:
            - version.txt
            - out.bin

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./bin
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(cat ./bin/version.txt)
            FILENAME=mega-drive-psg-envelopes-${VERSION}.bin
            mv ./bin/out.bin ./bin/${FILENAME}
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${VERSION} ./bin/${FILENAME}
workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - publish-github-release:
          requires:
            - hold
